services:
  - type: web
    name: smartbuyindia
    runtime: static
    branch: development/smartbuyindia-v2
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
