import { useEffect } from 'react';
import { Outlet, useLocation } from 'react-router-dom';
import Header from './Header.jsx';
import Footer from './Footer.jsx';
import { trackPageView } from '../utils/analytics.js';
import { organizationSchema } from '../utils/seo.js';
import { IS_DEMO_CONTENT } from '../config/content.js';

/**
 * App shell: demo ribbon + header, routed page content, footer.
 * Also owns the two cross-cutting behaviours every route needs —
 * scroll restoration and page-view tracking.
 */
export default function Layout() {
  const location = useLocation();
  const { pathname, search, hash } = location;

  // Scroll restoration. Hash anchors (FAQ sections, TOC links) win.
  useEffect(() => {
    if (hash) {
      const target = document.getElementById(hash.replace('#', ''));
      if (target) {
        // Wait a frame so the new route has painted.
        requestAnimationFrame(() => {
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        });
        return;
      }
    }
    window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
  }, [pathname, search, hash]);

  // Page views. Path + search only — no personal data, no referrer chain.
  useEffect(() => {
    trackPageView(`${pathname}${search}`);
  }, [pathname, search]);

  // Mark pages that pin a mobile CTA bar so content isn't hidden behind it.
  useEffect(() => {
    return () => document.body.classList.remove('has-mobile-cta');
  }, [pathname]);

  return (
    <>
      <a
        className="skip-link"
        href="#main"
        onClick={(event) => {
          // HashRouter owns the URL hash — scroll + focus instead of navigating.
          event.preventDefault();
          const main = document.getElementById('main');
          if (main) {
            main.focus();
            main.scrollIntoView({ block: 'start' });
          }
        }}
      >
        Skip to main content
      </a>
      <Header />
      <main id="main" tabIndex={-1}>
        <Outlet />
      </main>
      <Footer />
      {IS_DEMO_CONTENT && (
        <div className="sr-only" role="note">
          Organization schema and page metadata are generated by SmartBuyIndia. Content is demo
          placeholder data.
        </div>
      )}
      {/* Organization identity is present on every page. */}
      <OrganizationSchema />
    </>
  );
}

function OrganizationSchema() {
  useEffect(() => {
    const existing = document.getElementById('ld-organization');
    if (existing) return;
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.id = 'ld-organization';
    script.textContent = JSON.stringify(organizationSchema());
    document.head.appendChild(script);
  }, []);
  return null;
}
