import { Suspense, useEffect, useRef, useState } from 'react';
import { Outlet, useLocation } from 'react-router-dom';
import Header from './Header.jsx';
import Footer from './Footer.jsx';
import { trackPageView } from '../utils/analytics.js';
import { organizationSchema } from '../utils/seo.js';
import { IS_DEMO_CONTENT } from '../config/content.js';
import PageLoader from './PageLoader.jsx';

/**
 * App shell: demo ribbon + header, routed page content, footer.
 * Also owns the two cross-cutting behaviours every route needs —
 * scroll restoration and page-view tracking.
 */
export default function Layout() {
  const location = useLocation();
  const { pathname, search, hash } = location;
  const [routeTransition, setRouteTransition] = useState(false);
  const transitionStartedAt = useRef(0);

  // Show a brief branded transition when a shopper explicitly clicks an internal link.
  // This is separate from Suspense so the experience still feels intentional when route chunks
  // are already cached and navigation would otherwise be visually instant.
  useEffect(() => {
    const onInternalLinkClick = (event) => {
      if (event.defaultPrevented || event.button !== 0) return;
      if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;

      const link = event.target.closest?.('a[href]');
      if (!link) return;
      if (link.target === '_blank' || link.hasAttribute('download')) return;

      const href = link.getAttribute('href') || '';
      if (!href.startsWith('/') || href.startsWith('//') || href.startsWith('/#')) return;

      transitionStartedAt.current = performance.now();
      setRouteTransition(true);
    };

    document.addEventListener('click', onInternalLinkClick, true);
    return () => document.removeEventListener('click', onInternalLinkClick, true);
  }, []);

  useEffect(() => {
    if (!routeTransition) return undefined;

    // Safety timeout for same-page clicks or navigation cancelled by another handler.
    const timer = window.setTimeout(() => setRouteTransition(false), 700);
    return () => window.clearTimeout(timer);
  }, [routeTransition]);

  useEffect(() => {
    if (!routeTransition) return undefined;

    const elapsed = performance.now() - transitionStartedAt.current;
    const minimumVisibleMs = 320;
    const remaining = Math.max(0, minimumVisibleMs - elapsed);
    const timer = window.setTimeout(() => setRouteTransition(false), remaining);

    return () => window.clearTimeout(timer);
  }, [pathname, search, hash, routeTransition]);

  // Scroll restoration. Hash anchors (FAQ sections, TOC links) win.
  useEffect(() => {
    if (hash) {
      const target = document.getElementById(hash.replace('#', ''));
      if (target) {
        // Wait a frame so the new route has painted.
        requestAnimationFrame(() => {
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        });
        return;
      }
    }
    window.scrollTo({ top: 0, left: 0, behavior: 'auto' });
  }, [pathname, search, hash]);

  // Page views. Path + search only — no personal data, no referrer chain.
  useEffect(() => {
    trackPageView(`${pathname}${search}`);
  }, [pathname, search]);

  // Mark pages that pin a mobile CTA bar so content isn't hidden behind it.
  useEffect(() => {
    return () => document.body.classList.remove('has-mobile-cta');
  }, [pathname]);

  return (
    <>
      <a
        className="skip-link"
        href="#main"
        onClick={(event) => {
          // HashRouter owns the URL hash — scroll + focus instead of navigating.
          event.preventDefault();
          const main = document.getElementById('main');
          if (main) {
            main.focus();
            main.scrollIntoView({ block: 'start' });
          }
        }}
      >
        Skip to main content
      </a>
      <Header />
      {routeTransition && (
        <div className="route-transition" aria-hidden="true">
          <PageLoader />
        </div>
      )}
      <main id="main" tabIndex={-1}>
        <Suspense fallback={<PageLoader />}>
          <Outlet />
        </Suspense>
      </main>
      <Footer />
      {IS_DEMO_CONTENT && (
        <div className="sr-only" role="note">
          Organization schema and page metadata are generated by SmartBuyIndia. Content is demo
          placeholder data.
        </div>
      )}
      {/* Organization identity is present on every page. */}
      <OrganizationSchema />
    </>
  );
}

function OrganizationSchema() {
  useEffect(() => {
    const existing = document.getElementById('ld-organization');
    if (existing) return;
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.id = 'ld-organization';
    script.textContent = JSON.stringify(organizationSchema());
    document.head.appendChild(script);
  }, []);
  return null;
}
